services:

  build:
    image: maven:3.9.6-eclipse-temurin-21-alpine
    environment:
      MVN_PROFILE: github
      GIT_REPOSITORY_NAME: microkernel-core-system
      USERNAME: yoga1290
      ACCESS_TOKEN: ${GITHUB_TOKEN}
    command: /bin/sh +x ./ci/push-mvn-registry/mvn-install.sh
    working_dir: /usr/app
    volumes:
      - ./:/usr/app

  deploy-mvn-registry:
    image: maven:3.9.6-eclipse-temurin-21-alpine
    environment:
      MVN_PROFILE: github
      GIT_REPOSITORY_NAME: microkernel-core-system
      USERNAME: yoga1290
      ACCESS_TOKEN: ${GITHUB_TOKEN}
    command: /bin/sh +x ./ci/push-mvn-registry/mvn-deploy.sh
    working_dir: /usr/app
    volumes:
      - ./:/usr/app