FROM maven:3.9.6-eclipse-temurin-21-alpine

ENV GITHUB_REPOSITORY="spring-core-system"
ENV GITHUB_OWNER=GITHUB_OWNER:TODO
ENV GITHUB_TOKEN=GITHUB_TOKEN:TODO
ENV M2_SETTINGS_OUTPUT="/root/.m2"
# see https://hub.docker.com/_/maven

WORKDIR /usr/app
COPY . .

CMD 'bash' '+x' './deploy.sh'