# This is a basic workflow to help you get started with Actions

name: build-maven

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  push-maven:
    # The type of runner that the job will run on
    # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - name: Build and Push Maven
      env:
        MVN_PROFILE: github
        GIT_REPOSITORY_NAME: ${{github.repository}}
        USERNAME: ${{ github.repository_owner }}
        ACCESS_TOKEN: ${{ secrets.GH_PACKAGES }}
        DOCKER_FILE: ".//ci/push-mvn-registry/Dockerfile"
      run: |
        bash +x ./ci/push-mvn-registry/push-mvn-registry-on-docker.sh
